package org.example.project.navigation

sealed class Screens(val route: String) {
    object Splash : Screens("splash")
    object Login: Screens("login")
    object WelcomeScreen: Screens("welcome_screen")
    object RegisterScreen: Screens("register_screen")
    object OTPScreen: Screens("otp_screen")
    object OTPScreenRoute: Screens("otp_screen/{tempUserId}/{email}")
    object ForgetPasswordScreen: Screens("forget_password_screen")
    object NotificationListScreen: Screens("notification_list_screen")
    object TabBar: Screens("tab_bar")
    // Observation
    object ObservationListScreen : Screens("observation_list_screen")
    object ObservationDraftListScreen : Screens("observation_draft_list_screen")
    object CreateObservationScreen : Screens("create_observation_screen")
    object CreateIncidentScreen : Screens("create_incident_screen")
    object ObservationDetailsScreen : Screens("observation_details_screen")
    object ObservationDetailsScreenWithArgs : Screens("observation_details_screen/{observationId}")

    // Action Overview Modules
    object PreTaskListScreen : Screens("pre_task_list_screen")
    object CreatePreTaskScreen : Screens("create_pre_task_screen")
    object AuditInspectionListScreen : Screens("audit_inspection_list_screen")
    object CreateInspectionScreen : Screens("create_inspection_screen")
    object CreateInspectionScreenWithArgs : Screens("create_inspection_screen/{inspectionTypeId}/{inspectionTypeName}")
    object InspectionDetailScreen : Screens("inspection_detail_screen")
    object InspectionDetailScreenWithArgs : Screens("inspection_detail_screen/{inspectionId}")
    object PermitToWorkListScreen : Screens("permit_to_work_list_screen")
    object PermitDetailScreen : Screens("permit_detail_screen")
    object PermitDetailScreenWithArgs : Screens("permit_detail_screen/{permitId}")
    object CreatePermitScreen : Screens("create_permit_screen")
    object CreatePermitScreenWithArgs : Screens("create_permit_screen/{permitTypeId}/{permitTypeName}")
    object IncidentListScreen : Screens("incident_list_screen")
    object ViolationListScreen : Screens("violation_list_screen")
    object CreateViolationScreen : Screens("create_violation_screen")
    object TrainingListScreen : Screens("training_list_screen")
    object TrainingDetailScreen : Screens("training_detail_screen")
    object TrainingDetailScreenWithArgs : Screens("training_detail_screen/{trainingId}")
    object AssignedTrainingsScreen : Screens("assigned_trainings_screen")
    object TrainingVideoScreen : Screens("training_video_screen")
    object TrainingVideoScreenWithArgs : Screens("training_video_screen/{trainingId}")
    object QuizScreen : Screens("quiz_screen")
    object QuizScreenWithArgs : Screens("quiz_screen/{trainingId}")
    object TrainingScormScreen : Screens("training_scorm_screen")
    object TrainingScormScreenWithArgs : Screens("training_scorm_screen/{scormUrl}")
    object PendingActionListScreen : Screens("pending_action_list_screen")
    object ProfileScreen : Screens("profile_screen")
    object CreateProjectScreen : Screens("create_project_screen")
    object EditProjectScreen : Screens("edit_project_screen")
    object ProjectDetailScreen : Screens("project_detail_screen")
    object ProjectDetailScreenWithArgs : Screens("project_detail_screen/{groupId}/{groupCode}")

    object ChangePasswordScreen : Screens("change_password_screen")
    object ContactUsScreen : Screens("contact_us_screen")
    object AboutUsScreen : Screens("about_us_screen")
    object TermsOfUseScreen : Screens("terms_of_use_screen")
    object PrivacyPolicyScreen : Screens("privacy_policy_screen")
    object DeleteAccountScreen : Screens("delete_account_screen")
    
    // Lessons Learned
    object LessonsLearnedListScreen : Screens("lessons_learned_list_screen")
    object CreateLessonsLearnedScreen : Screens("create_lessons_learned_screen")
    
    // Toolbox Talks
    object ToolBoxTalkListScreen : Screens("toolbox_talk_list_screen")
    object CreateToolBoxTalkScreen : Screens("create_toolbox_talk_screen")
    object ToolBoxTalkDetailScreen : Screens("toolbox_talk_detail_screen")
    object ToolBoxTalkDetailScreenWithArgs : Screens("toolbox_talk_detail_screen/{toolboxTalkId}")
}
