package org.example.project.network

object ApiEndpoints {
    const val LOGIN = "user/login"
    const val FORGOT_PASSWORD = "forgot-password"
    const val REGISTER = "user/registration"
    const val VERIFY_OTP = "user/email-verify"
    const val USER_CHECKOUT = "generic/user-check"
    const val PROJECT_LIST = "v3/group/list"
    const val REFRESH_TOKEN = "token/refresh"
    const val HOME_CONTENT = "home/contents"

    const val NOTIFICATION_LIST = "v3/notification/list"
    const val USER_EDIT = "user/profile/edit"
    const val CREATE_PROJECT = "v3/group/create"
    const val VIEW_PROJECT = "v3/group/view"
    const val REQUEST_PROJECT_ACCESS = "v3/group/request-access"
    const val UPLOAD_IMAGE = "upload-image"
    const val PROJECT_DETAILS = "v3/group/details"
    const val INVITE_MEMBERS = "v3/group/invite-users"
    const val DELETE_PROJECT = "group/delete"
    const val EXIT_PROJECT = "group/exit"
    const val CHANGE_ROLE = "v3/group/role-change"
    const val REMOVE_MEMBER = "group/remove-member"
    const val HANDOVER_SUPERADMIN = "v3/group/handover/admin-rights"
    const val GENERAL_CONTENTS = "general/contents"
    const val CHANGE_PASSWORD = "change-password"
    const val DELETE_ACCOUNT_TERMS = "user/delete/terms"
    const val DELETE_ACCOUNT = "user/delete"
    const val DELETE_ACCOUNT_VERIFY = "user/delete-verify"
    const val CONTACT_SEND_MESSAGE = "contact/send-message"
    const val PENDING_ACTION_LIST = "v3/pendingAction/list"
    const val OBSERVATION_LIST = "v3/observation/list"
    const val FILTER_CONTENT = "filter-content"
    const val GROUP_USER_LIST = "v3/group/user-list"
    const val CREATE_OBSERVATION = "v3/observation/create"
    const val OBSERVATION_DETAIL = "v2/observation/detail"
}
